default: &default
 adapter: postgresql
 encoding: unicode

 # Matches name of postgres service in docker-compose.yml
 host: postgres

 username: <%= ENV.fetch("POSTGRES_USER") %>
 password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
 timeout: 5000

development:
 <<: *default
 database: <%= "pg_#{ENV.fetch("POSTGRES_DB")}_#{Rails.env}"  %>
